(define (filter pred lst) (cond ((null? lst) '()) ((pred (car lst)) (cons (car lst) (filter pred (cdr lst)))) (else (filter pred (cdr lst)))))
(define-record relationship subject relation object)
(define-record action-model success-prob cost)
(define-record state-var id val)
(define-record timeline-entry action-id start-time end-time)
(define-record eclass parent nodes)
(define-record plan-state executable metadata failed paused-at prev-tree current-time vars history-timeline current-blacklist next-node-id e-classes)
(define-record solution-node node-id content status tag shadow-state tried-methods-idx)
(define-record solution-tree nodes edges)
(define (prune-node tree target-id) (let* ((remaining-nodes (filter (lambda (n) (not (= (solution-node-node-id n) target-id))) (solution-tree-nodes tree))) (remaining-edges (filter (lambda (e) (and (not (= (car e) target-id)) (not (= (cdr e) target-id)))) (solution-tree-edges tree)))) (record-with make-solution-tree '(nodes edges) tree (nodes remaining-nodes) (edges remaining-edges))))
(define (alloc-node-id st) (let* ((new-id (plan-state-next-node-id st))) (cons (record-with make-plan-state '(executable metadata failed paused-at prev-tree current-time vars history-timeline current-blacklist next-node-id e-classes) st (next-node-id (+ new-id 1))) new-id)))
(define (add-to-blacklist st e) (record-with make-plan-state '(executable metadata failed paused-at prev-tree current-time vars history-timeline current-blacklist next-node-id e-classes) st (current-blacklist (cons e (plan-state-current-blacklist st)))))
